CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Categorias" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(200) NOT NULL,
    "Activo" boolean NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "CreadoPor" character varying(450) NOT NULL,
    "FechaModificacion" timestamp with time zone,
    "ModificadoPor" character varying(450),
    CONSTRAINT "PK_Categorias" PRIMARY KEY ("Id")
);

CREATE TABLE "Ordenes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Fecha" timestamp with time zone NOT NULL,
    "Estado" character varying(50) NOT NULL,
    "Total" numeric(18,2) NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "CreadoPor" character varying(450) NOT NULL,
    "FechaModificacion" timestamp with time zone,
    "ModificadoPor" character varying(450),
    CONSTRAINT "PK_Ordenes" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Productos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(200) NOT NULL,
    "Descripcion" character varying(2000),
    "Precio" numeric(18,2) NOT NULL,
    "Stock" integer NOT NULL,
    "CategoriaId" integer NOT NULL,
    "Activo" boolean NOT NULL,
    "FilaVersion" bytea NOT NULL DEFAULT '\x'::bytea,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "CreadoPor" character varying(450) NOT NULL,
    "FechaModificacion" timestamp with time zone,
    "ModificadoPor" character varying(450),
    CONSTRAINT "PK_Productos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Productos_Categorias_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES "Categorias" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "DetallesOrden" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrdenId" integer NOT NULL,
    "ProductoId" integer NOT NULL,
    "Cantidad" integer NOT NULL,
    "PrecioUnitario" numeric(18,2) NOT NULL,
    "Subtotal" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_DetallesOrden" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DetallesOrden_Ordenes_OrdenId" FOREIGN KEY ("OrdenId") REFERENCES "Ordenes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DetallesOrden_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_DetallesOrden_OrdenId" ON "DetallesOrden" ("OrdenId");

CREATE INDEX "IX_DetallesOrden_ProductoId" ON "DetallesOrden" ("ProductoId");

CREATE INDEX "IX_Productos_CategoriaId" ON "Productos" ("CategoriaId");
