<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GestionOrden.Domain\GestionOrden.Domain.csproj" />
    <ProjectReference Include="..\GestionOrden.Infrastructure\GestionOrden.Infrastructure.csproj" />
    <ProjectReference Include="..\GestionOrden.Persistencia\GestionOrden.Persistencia.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
